
const CURRENT_YEAR=new Date().getFullYear();
const luxuryBrands=["bmw","mercedes","mercedes-benz","audi","lexus","porsche","jaguar","land rover","range rover","cadillac","lincoln","infiniti","acura","volvo","tesla","genesis","maserati"];
const economyBrands=["toyota","honda","ford","chevrolet","chevy","nissan","hyundai","kia","mazda","subaru","volkswagen","vw","dodge","jeep","ram","gmc","buick","mitsubishi"];
const highLaborZipPrefixes=["90","91","92","93","94","95","96","97","98","99","10","11","20","21","22","70","71","80","81"];
const repairData={
checkEngine:{label:"General check engine diagnosis",keywords:["check engine","engine light","cel","code","codes","scanner","emissions"],baseMin:90,baseMax:650,baseScore:68,urgency:"Medium",drive:"Usually okay for short trips if the light is steady. Do not drive if the light is flashing.",causes:[["EVAP leak / gas cap",45,50,220,"low"],["Oxygen sensor",40,180,500,"medium"],["Misfire diagnosis",35,150,650,"medium"],["Catalytic converter efficiency code",18,750,2500,"high"]]},
shaking:{label:"Shaking / vibration / misfire feeling",keywords:["shake","shaking","vibrate","vibration","rough idle","misfire","stutter","stuttering","jerk","jerking","hesitate","hesitation"],baseMin:150,baseMax:600,baseScore:70,urgency:"Medium",drive:"Short distances only if mild. Avoid hard acceleration and high speeds until checked.",causes:[["Bad coil packs",55,150,500,"medium"],["Worn spark plugs",50,100,350,"low"],["Vacuum / boost leak",35,120,650,"medium"],["Engine mounts",22,300,900,"medium"]]},
overheating:{label:"Overheating / cooling system issue",keywords:["overheat","overheating","hot","temperature","temp gauge","coolant boiling","steam","radiator"],baseMin:250,baseMax:1400,baseScore:38,urgency:"High",drive:"Do not drive while overheating. Pull over, shut the car off, and let it cool.",causes:[["Thermostat",50,180,500,"medium"],["Water pump",42,500,1300,"high"],["Radiator / coolant leak",38,250,1000,"high"],["Head gasket concern",10,1500,4500,"high"]]},
slowAcceleration:{label:"No power / slow acceleration",keywords:["slow acceleration","no power","loss of power","boost","turbo","wastegate","limp mode","won't accelerate","doesnt accelerate","doesn't accelerate","sluggish"],baseMin:120,baseMax:1200,baseScore:62,urgency:"Medium",drive:"Drive gently. Avoid highway pulls, heavy throttle, and boost until inspected.",causes:[["Boost / vacuum leak",50,100,650,"medium"],["Dirty MAF/MAP sensor",42,80,320,"low"],["Fuel delivery issue",28,250,950,"medium"],["Turbo / wastegate issue",20,650,2400,"high"]]},
hardStart:{label:"Hard start issue",keywords:["hard start","hard to start","long crank","cranks","takes long to start","starting problem"],baseMin:120,baseMax:850,baseScore:66,urgency:"Medium",drive:"Usually driveable once started, but the issue can leave you stranded.",causes:[["Weak battery",55,120,280,"low"],["Starter",38,350,800,"medium"],["Fuel pump / fuel delivery",30,300,1100,"medium"],["Ignition switch / relay",18,150,500,"medium"]]},
noCrank:{label:"No crank / no start",keywords:["no crank","no start","wont start","won't start","dead","clicking","clicks","nothing happens"],baseMin:120,baseMax:1100,baseScore:48,urgency:"High",drive:"Not driveable until diagnosed.",causes:[["Dead battery",50,120,280,"low"],["Starter",35,350,850,"medium"],["Ignition / relay / fuse",25,100,500,"medium"],["Security / immobilizer issue",12,180,900,"medium"]]},
brakes:{label:"Brake noise / brake repair",keywords:["brake","brakes","squeak","squeaking","grinding","rotor","rotors","pads","soft pedal","stopping"],baseMin:180,baseMax:800,baseScore:64,urgency:"Medium",drive:"Drive carefully. If there is grinding, pulling, or a soft pedal, stop driving.",causes:[["Brake pads",60,180,420,"medium"],["Pads and rotors",45,350,850,"medium"],["Caliper issue",20,450,1100,"high"],["Brake fluid / hydraulic issue",12,120,700,"high"]]},
acWarm:{label:"AC not blowing cold",keywords:["ac","a/c","air conditioning","not cold","hot air","warm air","compressor"],baseMin:120,baseMax:1300,baseScore:78,urgency:"Low",drive:"Safe to drive, but defrosting and comfort may be affected.",causes:[["Low refrigerant",55,120,300,"low"],["AC leak",42,250,850,"medium"],["Compressor",25,750,1700,"medium"],["Blend door / actuator",18,180,650,"low"]]},
battery:{label:"Battery / charging issue",keywords:["battery","dies","keeps dying","alternator","jump start","jumped","dead battery","charging"],baseMin:120,baseMax:800,baseScore:72,urgency:"Medium",drive:"Driveable if it starts, but it may leave you stranded again.",causes:[["Bad battery",60,120,280,"low"],["Alternator",40,400,900,"medium"],["Parasitic electrical drain",25,150,800,"medium"],["Corroded terminals / bad cable",22,80,320,"low"]]},
oilLeak:{label:"Oil leak / burning oil",keywords:["oil leak","leaking oil","burning oil","oil smell","oil on ground","low oil","smoke oil"],baseMin:120,baseMax:1200,baseScore:55,urgency:"Medium",drive:"Check oil level before driving. Do not drive if oil is very low or the leak is heavy.",causes:[["Valve cover gasket",45,250,800,"medium"],["Oil pan gasket",32,350,1200,"medium"],["Loose drain plug / oil filter",30,40,180,"low"],["Rear main seal",12,800,2200,"high"]]},
coolantLeak:{label:"Coolant leak",keywords:["coolant leak","leaking coolant","antifreeze","green fluid","pink fluid","coolant low"],baseMin:150,baseMax:1400,baseScore:45,urgency:"High",drive:"Do not drive if coolant level drops or temperature rises.",causes:[["Radiator hose",45,150,400,"medium"],["Radiator",35,450,1100,"high"],["Water pump",28,500,1300,"high"],["Heater core",12,800,1800,"high"]]},
hardShift:{label:"Transmission shifting issue",keywords:["transmission","hard shift","shifting hard","jerk shift","slipping","gear","gears","delayed shift"],baseMin:180,baseMax:2200,baseScore:40,urgency:"High",drive:"Drive gently and avoid long trips. Transmission issues can get expensive fast.",causes:[["Low / dirty transmission fluid",42,180,450,"medium"],["Sensor / solenoid issue",35,300,1000,"medium"],["Transmission mount",22,250,800,"medium"],["Internal transmission wear",18,1500,5500,"high"]]},
suspensionNoise:{label:"Suspension noise / clunk",keywords:["suspension","clunk","clunking","rattle","rattling","pothole","struts","shocks","ball joint","control arm"],baseMin:180,baseMax:1400,baseScore:62,urgency:"Medium",drive:"Drive carefully. Avoid potholes and high speeds until inspected.",causes:[["Sway bar links / bushings",45,180,450,"low"],["Struts / shocks",38,450,1300,"medium"],["Control arms / ball joints",28,450,1400,"high"],["Wheel bearing",20,350,900,"high"]]},
steeringShake:{label:"Steering shake / alignment issue",keywords:["steering shake","wheel shakes","steering wheel","alignment","pulling","pulls","wheel balance","tire balance"],baseMin:80,baseMax:900,baseScore:70,urgency:"Medium",drive:"Drive carefully. If shaking is severe, avoid highway speeds.",causes:[["Wheel balance",55,80,180,"low"],["Bent wheel / bad tire",35,180,650,"medium"],["Brake rotor vibration",30,300,800,"medium"],["Suspension wear",20,350,1200,"medium"]]},
fuelSmell:{label:"Fuel smell / fuel leak concern",keywords:["fuel smell","gas smell","smells like gas","gas leak","fuel leak","gasoline"],baseMin:120,baseMax:1200,baseScore:35,urgency:"High",drive:"Do not ignore fuel smell. Avoid driving if smell is strong or fuel is leaking.",causes:[["Fuel line leak",35,150,900,"high"],["EVAP leak",30,120,500,"medium"],["Fuel injector leak",25,300,1200,"high"],["Fuel tank / filler neck",15,350,1500,"high"]]},
engineNoise:{label:"Engine knocking / ticking",keywords:["knock","knocking","tick","ticking","engine noise","rod knock","lifter","metal noise"],baseMin:120,baseMax:3500,baseScore:30,urgency:"High",drive:"Avoid driving until inspected. Engine noises can become serious quickly.",causes:[["Low oil / oil pressure concern",35,80,600,"high"],["Lifter / valve train tick",28,400,1800,"medium"],["Rod knock / internal engine wear",15,2500,9000,"high"],["Exhaust leak mistaken as tick",18,150,700,"medium"]]}
};
Object.values(repairData).forEach(i=>{i.causes=i.causes.map(c=>({name:c[0],prob:c[1],min:c[2],max:c[3],sev:c[4]}));});
function money(n){return "$"+Math.round(Number(n)).toLocaleString();}
function clean(s){return String(s||"").trim().toLowerCase();}
function titleCase(s){return String(s||"").trim().split(" ").filter(Boolean).map(w=>w.charAt(0).toUpperCase()+w.slice(1).toLowerCase()).join(" ");}
function clamp(n,min,max){return Math.min(max,Math.max(min,n));}
function matchIssue(symptoms){const text=clean(symptoms);let bestKey="checkEngine",bestScore=0;Object.entries(repairData).forEach(([key,data])=>{let score=0;data.keywords.forEach(k=>{if(text.includes(k))score+=k.length>7?3:2;});data.label.toLowerCase().split(/[\s/]+/).forEach(w=>{if(w.length>3&&text.includes(w))score+=1;});if(score>bestScore){bestScore=score;bestKey=key;}});if(bestScore===0)return{key:"checkEngine",confidence:"Low",note:"The system could not clearly match the symptom, so it used a general diagnostic estimate."};if(bestScore<=2)return{key:bestKey,confidence:"Medium",note:"The system found a possible match, but more symptom details would improve accuracy."};return{key:bestKey,confidence:"High",note:"The system matched your written symptoms to a repair category."};}
function getBrandFactor(make){const m=clean(make);if(luxuryBrands.some(b=>m.includes(b)))return{factor:1.35,label:"Luxury brand",note:"Higher parts and labor expectations."};if(economyBrands.some(b=>m.includes(b)))return{factor:1,label:"Common brand",note:"Standard parts and labor expectations."};return{factor:1.12,label:"Less common brand",note:"Parts availability may increase cost."};}
function getAgeFactor(year,engineType){const age=Math.max(0,CURRENT_YEAR-Number(year||CURRENT_YEAR));let factor=1,label="Modern vehicle",note="Normal age factor.";if(age>=45){factor=1.35;label="Classic vehicle";note="Older parts and extra labor may apply.";}else if(age>=25){factor=1.22;label="Older vehicle";note="Age may increase labor and parts difficulty.";}else if(age>=15){factor=1.12;label="High age";note="Wear and fasteners may add labor.";}else if(age<=3){factor=1.08;label="Newer vehicle";note="Electronics and parts may cost more.";}if(engineType==="classic")factor=Math.max(factor,1.30);return{factor,label,note,age};}
function getMileageFactor(mileage){const mi=Number(mileage||0);if(mi>=200000)return{factor:1.18,label:"Very high mileage",note:"More related wear risk."};if(mi>=150000)return{factor:1.12,label:"High mileage",note:"More diagnostic and wear risk."};if(mi>=90000)return{factor:1.06,label:"Moderate mileage",note:"Some wear-related risk."};if(mi>0&&mi<30000)return{factor:1.03,label:"Low mileage",note:"Lower wear but parts can still fail."};return{factor:1,label:"Normal mileage",note:"No major mileage adjustment."};}
function getEngineFactor(engineType,issueKey){const special={standard:1,turbo:1.10,diesel:1.22,hybrid:1.18,electric:1.28,classic:1.25};let factor=special[engineType]||1;if(engineType==="turbo"&&["slowAcceleration","shaking","checkEngine"].includes(issueKey))factor+=.08;return{factor,label:titleCase(engineType),note:"Engine type affects labor and diagnostics."};}
function getConditionFactor(condition){const map={clean:{factor:.97,label:"Maintained",note:"Slightly lower repair risk."},average:{factor:1,label:"Average condition",note:"Standard condition factor."},rough:{factor:1.18,label:"Rough condition",note:"More labor or related repairs possible."},modified:{factor:1.20,label:"Modified vehicle",note:"Mods can complicate diagnosis."}};return map[condition]||map.average;}
function getLocationFactor(zip){const z=String(zip||"").trim();if(z.startsWith("799")||z.startsWith("88"))return{factor:.96,label:"Regional labor",note:"Local market adjustment applied."};if(highLaborZipPrefixes.some(p=>z.startsWith(p)))return{factor:1.12,label:"Higher labor market",note:"Higher average labor pricing."};if(z.startsWith("78")||z.startsWith("77")||z.startsWith("75")||z.startsWith("76"))return{factor:1,label:"Texas market",note:"Standard regional labor pricing."};return{factor:1.05,label:"General market",note:"Estimated national market adjustment."};}
function getFormData(){return{year:document.getElementById("year")?.value||"",make:document.getElementById("make")?.value||"",model:document.getElementById("model")?.value||"",mileage:document.getElementById("mileage")?.value||"",zip:document.getElementById("zip")?.value||"",engineType:document.getElementById("engineType")?.value||"standard",condition:document.getElementById("condition")?.value||"average",symptoms:document.getElementById("symptoms")?.value||"",quote:document.getElementById("quote")?.value||""};}
function validateForm(data){const required=[["year","year"],["make","make"],["model","model"],["mileage","mileage"],["symptoms","what is going on with the car"],["quote","mechanic quote"]];for(const [key,label] of required){if(!String(data[key]||"").trim()){alert("Please enter the "+label+".");return false;}}return true;}
function calculateEstimate(data){const matched=matchIssue(data.symptoms);const issueKey=matched.key;const issue=repairData[issueKey];const year=Number(data.year||CURRENT_YEAR),mileage=Number(data.mileage||0),quote=Number(data.quote||0);const brand=getBrandFactor(data.make),age=getAgeFactor(year,data.engineType),mileageF=getMileageFactor(mileage),engine=getEngineFactor(data.engineType,issueKey),condition=getConditionFactor(data.condition),location=getLocationFactor(data.zip);const totalFactor=brand.factor*age.factor*mileageF.factor*engine.factor*condition.factor*location.factor;const adjustedMin=Math.max(0,issue.baseMin*totalFactor);const adjustedMax=Math.max(adjustedMin+20,issue.baseMax*totalFactor);const quoteRatio=quote>0?quote/adjustedMax:0;const score=clamp(Math.round(issue.baseScore-(quoteRatio>1?quoteRatio*10:0)-(issue.urgency==="High"?8:0)+(condition.factor<1?4:0)),10,95);return{...data,issueKey,matched,issue,year,mileage,quote,brand,age,mileageF,engine,condition,location,totalFactor,adjustedMin,adjustedMax,quoteRatio,score};}
function getVerdict(calc){const quote=calc.quote,min=calc.adjustedMin,max=calc.adjustedMax;if(quote<min*.65)return{label:"VERY LOW",type:"warn",desc:"This quote is unusually low. Confirm it includes parts, labor, diagnostic fees, taxes, and the full repair.",risk:"Low quote risk",angle:-20};if(quote<=max*1.15)return{label:"FAIR",type:"good",desc:"Your quote is within the expected adjusted range. Still ask for parts, labor, warranty, and diagnostic proof.",risk:"Low price risk",angle:-42};if(quote<=max*1.65)return{label:"HIGH",type:"warn",desc:"Your quote is above the expected adjusted range. Ask for a full breakdown and consider a second opinion.",risk:"Medium price risk",angle:0};return{label:"OVERPRICED",type:"bad",desc:"This quote is much higher than the adjusted range. Get a second opinion before approving the repair.",risk:"High price risk",angle:48};}
function submitEstimate(event){event.preventDefault();const data=getFormData();if(!validateForm(data))return;const calc=calculateEstimate(data);localStorage.setItem("fixsmartEstimate",JSON.stringify(calc));window.location.href="results.html";}
function loadResults(){const saved=localStorage.getItem("fixsmartEstimate");if(!saved){document.getElementById("vehicleLine").textContent="No estimate found. Please start a new estimate.";return;}const calc=JSON.parse(saved);const verdict=getVerdict(calc);document.getElementById("vehicleLine").textContent=`${calc.year} ${titleCase(calc.make)} ${calc.model} · ${Number(calc.mileage).toLocaleString()} miles · Matched to: ${calc.issue.label}`;document.getElementById("matchLine").textContent=`Symptom match confidence: ${calc.matched.confidence}. ${calc.matched.note}`;const verdictText=document.getElementById("verdictText");verdictText.textContent=verdict.label;verdictText.className="verdict";if(verdict.type==="good")verdictText.classList.add("good");if(verdict.type==="warn")verdictText.classList.add("warn");document.getElementById("verdictDesc").textContent=verdict.desc;document.getElementById("fairRange").textContent=`${money(calc.adjustedMin)} – ${money(calc.adjustedMax)}`;const quoteDisplay=document.getElementById("quoteDisplay");quoteDisplay.textContent=money(calc.quote);quoteDisplay.className="quote-money";if(verdict.type==="good")quoteDisplay.classList.add("good");if(verdict.type==="warn")quoteDisplay.classList.add("warn");document.getElementById("needle").style.transform=`rotate(${verdict.angle}deg)`;document.getElementById("riskLabel").textContent=verdict.risk;renderAdjustments(calc);renderCauseTable(calc);renderCards(calc,verdict);const leadMessage=document.getElementById("leadMessage");if(leadMessage)leadMessage.value=`${calc.year} ${titleCase(calc.make)} ${calc.model} - ${calc.issue.label}. User wrote: "${calc.symptoms}". Quote: ${money(calc.quote)}. Estimated fair range: ${money(calc.adjustedMin)} - ${money(calc.adjustedMax)}.`;}
function renderAdjustments(calc){const grid=document.getElementById("adjustmentGrid");if(!grid)return;const items=[{name:"Matched issue",value:calc.issue.label,note:calc.matched.note},{name:calc.brand.label,value:calc.brand.factor,note:calc.brand.note},{name:calc.age.label,value:calc.age.factor,note:calc.age.note},{name:calc.mileageF.label,value:calc.mileageF.factor,note:calc.mileageF.note},{name:calc.engine.label,value:calc.engine.factor,note:calc.engine.note},{name:calc.condition.label,value:calc.condition.factor,note:calc.condition.note},{name:calc.location.label,value:calc.location.factor,note:calc.location.note},{name:"Total factor",value:calc.totalFactor,note:"Base range multiplied by vehicle factors."}];grid.innerHTML="";items.forEach(item=>{const div=document.createElement("div");div.className="adjustment";const value=typeof item.value==="number"?`×${Number(item.value).toFixed(2)}`:item.value;div.innerHTML=`<strong>${item.name} ${value}</strong><span>${item.note}</span>`;grid.appendChild(div);});}
function adjustedCause(cause,factor){return{...cause,min:Math.max(0,cause.min*factor),max:Math.max(cause.min*factor+20,cause.max*factor)};}
function renderCauseTable(calc){const table=document.getElementById("causeTable");if(!table)return;table.innerHTML="";calc.issue.causes.map(c=>adjustedCause(c,calc.totalFactor)).forEach(cause=>{const row=document.createElement("tr");row.innerHTML=`<td>${cause.name}</td><td class="probability">${cause.prob}%</td><td class="cost">${money(cause.min)} – ${money(cause.max)}</td><td class="sev-${cause.sev}">${cause.sev.toUpperCase()}</td>`;table.appendChild(row);});}
function renderCards(calc,verdict){const scoreBox=document.getElementById("repairScore");scoreBox.textContent=`${calc.score}/100`;scoreBox.className=calc.score>=70?"big-green":calc.score>=45?"big-yellow":"big-red";document.getElementById("scoreText").textContent=calc.score>=70?"This repair is usually worth considering if the quote is fair and the vehicle is in good condition.":calc.score>=45?"This repair may be worth doing, but compare quotes and confirm the diagnosis.":"High risk repair. Get a second opinion and compare the repair cost against the vehicle value.";document.getElementById("driveText").textContent=calc.issue.drive;const redFlags=document.getElementById("redFlags");if(verdict.type==="bad")redFlags.innerHTML="<li>Quote is far above adjusted fair range.</li><li>Ask for parts and labor split.</li><li>Do not approve extra repairs without proof.</li>";else if(verdict.type==="warn")redFlags.innerHTML="<li>Price or quote details need review.</li><li>Ask why the quote differs from the expected range.</li><li>Compare one more shop.</li>";else redFlags.innerHTML="<li>Quote appears normal.</li><li>Still ask for warranty details.</li><li>Keep the written estimate.</li>";if(calc.issue.urgency==="High")redFlags.innerHTML+="<li>High urgency issue. Do not delay inspection.</li>";document.getElementById("nextSteps").innerHTML=`<li>Ask the shop what test confirmed the diagnosis.</li><li>Ask for written parts, labor, diagnostic fee, tax, and warranty details.</li><li>${verdict.type==="bad"?"Get a second quote before approving the repair.":"If the shop explains the diagnosis clearly, the quote may be reasonable."}</li><li>Compare the repair cost against the vehicle value before paying for major repairs.</li>`;}
function openLeadModal(){const modal=document.getElementById("leadModal");if(modal)modal.style.display="flex";}
function closeLeadModal(){const modal=document.getElementById("leadModal");if(modal)modal.style.display="none";}
document.addEventListener("DOMContentLoaded",()=>{const form=document.getElementById("estimateForm");if(form)form.addEventListener("submit",submitEstimate);if(document.body.dataset.page==="results")loadResults();});
